// src/types/database.ts
// This file will be auto-generated by Supabase CLI
// For now, we define the types manually

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            profiles: {
                Row: {
                    id: string
                    email: string
                    full_name: string | null
                    avatar_url: string | null
                    phone: string | null
                    role: 'customer' | 'admin'
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id: string
                    email: string
                    full_name?: string | null
                    avatar_url?: string | null
                    phone?: string | null
                    role?: 'customer' | 'admin'
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    email?: string
                    full_name?: string | null
                    avatar_url?: string | null
                    phone?: string | null
                    role?: 'customer' | 'admin'
                    created_at?: string
                    updated_at?: string
                }
            }
            categories: {
                Row: {
                    id: string
                    name: string
                    slug: string
                    description: string | null
                    image_url: string | null
                    parent_id: string | null
                    sort_order: number
                    is_active: boolean
                    created_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    slug: string
                    description?: string | null
                    image_url?: string | null
                    parent_id?: string | null
                    sort_order?: number
                    is_active?: boolean
                    created_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    slug?: string
                    description?: string | null
                    image_url?: string | null
                    parent_id?: string | null
                    sort_order?: number
                    is_active?: boolean
                    created_at?: string
                }
            }
            products: {
                Row: {
                    id: string
                    name: string
                    slug: string
                    description: string | null
                    short_description: string | null
                    base_price: number
                    compare_at_price: number | null
                    category_id: string | null
                    is_active: boolean
                    is_featured: boolean
                    meta_title: string | null
                    meta_description: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    slug: string
                    description?: string | null
                    short_description?: string | null
                    base_price: number
                    compare_at_price?: number | null
                    category_id?: string | null
                    is_active?: boolean
                    is_featured?: boolean
                    meta_title?: string | null
                    meta_description?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    slug?: string
                    description?: string | null
                    short_description?: string | null
                    base_price?: number
                    compare_at_price?: number | null
                    category_id?: string | null
                    is_active?: boolean
                    is_featured?: boolean
                    meta_title?: string | null
                    meta_description?: string | null
                    created_at?: string
                    updated_at?: string
                }
            }
            product_images: {
                Row: {
                    id: string
                    product_id: string
                    url: string
                    alt_text: string | null
                    sort_order: number
                    is_primary: boolean
                    created_at: string
                }
                Insert: {
                    id?: string
                    product_id: string
                    url: string
                    alt_text?: string | null
                    sort_order?: number
                    is_primary?: boolean
                    created_at?: string
                }
                Update: {
                    id?: string
                    product_id?: string
                    url?: string
                    alt_text?: string | null
                    sort_order?: number
                    is_primary?: boolean
                    created_at?: string
                }
            }
            product_variants: {
                Row: {
                    id: string
                    product_id: string
                    name: string
                    sku: string
                    price: number | null
                    attributes: Json
                    created_at: string
                }
                Insert: {
                    id?: string
                    product_id: string
                    name: string
                    sku: string
                    price?: number | null
                    attributes?: Json
                    created_at?: string
                }
                Update: {
                    id?: string
                    product_id?: string
                    name?: string
                    sku?: string
                    price?: number | null
                    attributes?: Json
                    created_at?: string
                }
            }
            inventory: {
                Row: {
                    id: string
                    variant_id: string
                    quantity: number
                    reserved_quantity: number
                    low_stock_threshold: number
                    updated_at: string
                }
                Insert: {
                    id?: string
                    variant_id: string
                    quantity?: number
                    reserved_quantity?: number
                    low_stock_threshold?: number
                    updated_at?: string
                }
                Update: {
                    id?: string
                    variant_id?: string
                    quantity?: number
                    reserved_quantity?: number
                    low_stock_threshold?: number
                    updated_at?: string
                }
            }
            carts: {
                Row: {
                    id: string
                    user_id: string | null
                    session_id: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id?: string | null
                    session_id?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string | null
                    session_id?: string | null
                    created_at?: string
                    updated_at?: string
                }
            }
            cart_items: {
                Row: {
                    id: string
                    cart_id: string
                    variant_id: string
                    quantity: number
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    cart_id: string
                    variant_id: string
                    quantity?: number
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    cart_id?: string
                    variant_id?: string
                    quantity?: number
                    created_at?: string
                    updated_at?: string
                }
            }
            wishlists: {
                Row: {
                    id: string
                    user_id: string
                    created_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    created_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    created_at?: string
                }
            }
            wishlist_items: {
                Row: {
                    id: string
                    wishlist_id: string
                    product_id: string
                    created_at: string
                }
                Insert: {
                    id?: string
                    wishlist_id: string
                    product_id: string
                    created_at?: string
                }
                Update: {
                    id?: string
                    wishlist_id?: string
                    product_id?: string
                    created_at?: string
                }
            }
            addresses: {
                Row: {
                    id: string
                    user_id: string
                    label: string | null
                    full_name: string
                    phone: string | null
                    street_address: string
                    apartment: string | null
                    city: string
                    state: string
                    postal_code: string
                    country: string
                    is_default: boolean
                    created_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    label?: string | null
                    full_name: string
                    phone?: string | null
                    street_address: string
                    apartment?: string | null
                    city: string
                    state: string
                    postal_code: string
                    country?: string
                    is_default?: boolean
                    created_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    label?: string | null
                    full_name?: string
                    phone?: string | null
                    street_address?: string
                    apartment?: string | null
                    city?: string
                    state?: string
                    postal_code?: string
                    country?: string
                    is_default?: boolean
                    created_at?: string
                }
            }
            orders: {
                Row: {
                    id: string
                    order_number: string
                    user_id: string | null
                    guest_email: string | null
                    status: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded'
                    subtotal: number
                    tax_amount: number
                    shipping_amount: number
                    discount_amount: number
                    total: number
                    shipping_address: Json
                    billing_address: Json | null
                    payment_intent_id: string | null
                    payment_status: 'pending' | 'paid' | 'failed' | 'refunded'
                    notes: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    order_number: string
                    user_id?: string | null
                    guest_email?: string | null
                    status?: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded'
                    subtotal: number
                    tax_amount?: number
                    shipping_amount?: number
                    discount_amount?: number
                    total: number
                    shipping_address: Json
                    billing_address?: Json | null
                    payment_intent_id?: string | null
                    payment_status?: 'pending' | 'paid' | 'failed' | 'refunded'
                    notes?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    order_number?: string
                    user_id?: string | null
                    guest_email?: string | null
                    status?: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded'
                    subtotal?: number
                    tax_amount?: number
                    shipping_amount?: number
                    discount_amount?: number
                    total?: number
                    shipping_address?: Json
                    billing_address?: Json | null
                    payment_intent_id?: string | null
                    payment_status?: 'pending' | 'paid' | 'failed' | 'refunded'
                    notes?: string | null
                    created_at?: string
                    updated_at?: string
                }
            }
            order_items: {
                Row: {
                    id: string
                    order_id: string
                    variant_id: string
                    product_name: string
                    variant_name: string
                    quantity: number
                    unit_price: number
                    total_price: number
                    created_at: string
                }
                Insert: {
                    id?: string
                    order_id: string
                    variant_id: string
                    product_name: string
                    variant_name: string
                    quantity: number
                    unit_price: number
                    total_price: number
                    created_at?: string
                }
                Update: {
                    id?: string
                    order_id?: string
                    variant_id?: string
                    product_name?: string
                    variant_name?: string
                    quantity?: number
                    unit_price?: number
                    total_price?: number
                    created_at?: string
                }
            }
            reviews: {
                Row: {
                    id: string
                    product_id: string
                    user_id: string
                    rating: number
                    title: string | null
                    comment: string | null
                    is_verified_purchase: boolean
                    is_approved: boolean
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    product_id: string
                    user_id: string
                    rating: number
                    title?: string | null
                    comment?: string | null
                    is_verified_purchase?: boolean
                    is_approved?: boolean
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    product_id?: string
                    user_id?: string
                    rating?: number
                    title?: string | null
                    comment?: string | null
                    is_verified_purchase?: boolean
                    is_approved?: boolean
                    created_at?: string
                    updated_at?: string
                }
            }
        }
        Views: {
            [_ in never]: never
        }
        Functions: {
            [_ in never]: never
        }
        Enums: {
            [_ in never]: never
        }
    }
}

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']
